
GET http://10.100.126.237/sicec.gateway/Contadores/GetTotalMesaJuez

### GET
GET  http://10.100.126.237/sicec.gateway/FormLight/GetAll

###
GET http://10.100.126.237/sicec.gateway/FormLight/GetAll

###
GET http://localhost:5283/Contadores/GetEstatus

### 
GET http://localhost:5283/MovConfiguracion/GetMovConfiguracion
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5NzIxMDg1MSwiZXhwIjoxNjk3Mjk3MjUxLCJpYXQiOjE2OTcyMTA4NTF9.NVxkpyyj_Ccf6TLgypDw1epYpn9J4ynzughK8eMGxgw


### 
GET http://10.100.126.237/sicec.gateway/Contadores/GetTotalMesaJuez
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5NzIxMDg1MSwiZXhwIjoxNjk3Mjk3MjUxLCJpYXQiOjE2OTcyMTA4NTF9.NVxkpyyj_Ccf6TLgypDw1epYpn9J4ynzughK8eMGxgw

### 
GET http://localhost:5283/Contadores/GetTotalMesaJuez
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5NzIxMDg1MSwiZXhwIjoxNjk3Mjk3MjUxLCJpYXQiOjE2OTcyMTA4NTF9.NVxkpyyj_Ccf6TLgypDw1epYpn9J4ynzughK8eMGxgw

### OK - Primer Bloque
GET http://localhost:5283/Contadores/GetTotalMesaJuez
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5NzQ4ODEzOCwiZXhwIjoxNjk3NTc0NTM4LCJpYXQiOjE2OTc0ODgxMzh9.OATExh6yg7wHC65CRMxn0-_9kv1fQWLHJllDj5SKx8w

### OK - Ultima sección
GET http://localhost:5283/Contadores/GetTotalesMesa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5NzIxMDg1MSwiZXhwIjoxNjk3Mjk3MjUxLCJpYXQiOjE2OTcyMTA4NTF9.NVxkpyyj_Ccf6TLgypDw1epYpn9J4ynzughK8eMGxgw

### OK - Listado de la tabla
GET http://localhost:5283/Contadores/TotalMesasJuez
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5ODI1ODAzOSwiZXhwIjoxNjk4MzQ0NDM5LCJpYXQiOjE2OTgyNTgwMzl9.jfGr33f43mEHrKRQ5jfyWCLb8_yGaCmxiL3uvElthAA

### OK - Listado de la tabla
GET http://10.100.126.237/sicec.gateway/Contadores/GetTotalesMesa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5ODI1ODAzOSwiZXhwIjoxNjk4MzQ0NDM5LCJpYXQiOjE2OTgyNTgwMzl9.jfGr33f43mEHrKRQ5jfyWCLb8_yGaCmxiL3uvElthAA

### OK - Listado de la tabla
GET http://10.100.126.237/sicec.gateway/Casos/GetCasosDetalleJPa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsYXNhbnRhbmEiLCJ1bmlxdWVfbmFtZSI6Ikx1aXMgQW5kcmVzIFNhbnRhbmEgUmV5ZXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyMzc0MjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zeXN0ZW0iOiIxMSIsIm5iZiI6MTY5ODI1ODAzOSwiZXhwIjoxNjk4MzQ0NDM5LCJpYXQiOjE2OTgyNTgwMzl9.jfGr33f43mEHrKRQ5jfyWCLb8_yGaCmxiL3uvElthAA


